name = "SpaceLib"
uuid = "fb1af579-3fc7-4df4-a3e6-ebb5d9b870c9"
authors = ["Rhahi <git@rhahi.com>"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
